def py_add(a: int, b: int) -> int: ...
def zig_add(a: int, b: int) -> int: ...

class PyForest2D:
    def __init__(self, domain_size: tuple[int, int], periodic_domain: tuple[bool, bool]) -> None: ...
    def __dealloc__(self): ...
